const test = require("node:test");
const assert = require("node:assert/strict");
const { createServiceCompletionService, completionKey } = require("../src/services/serviceCompletion");

const booking = { _id: "b1", bookingReference: "BR-1", productTitle: "Tour", bokunProductId: "P-1", travelDate: "2026-09-15", amount: 100, currency: "USD", pricingSnapshot: { finalPayable: 100, currency: "USD" } };
const harness = (bookingOverride = {}) => { const rows = []; const audit = []; const currentBooking = { ...booking, ...bookingOverride }; const completion = { find: () => ({ sort: () => ({ limit: () => ({ lean: async () => rows }) }) }), findOne: async ({ completionKey } = {}) => rows.find((row) => row.completionKey === completionKey) || null, create: async (input) => { const row = { _id: `c${rows.length + 1}`, ...input, save: async function save() { return this; }, lean: async function lean() { return this; } }; rows.push(row); return row; }, findById: async (id) => rows.find((row) => row._id === id) || null }; const recognition = { find: () => ({ sort: () => ({ lean: async () => [] }) }) }; const bookings = { findOne: () => ({ lean: async () => currentBooking }), findById: () => ({ lean: async () => currentBooking }) }; return { service: createServiceCompletionService({ CompletionModel: completion, RecognitionModel: recognition, BookingModel: bookings, RevenueService: { preview: async ({ completionId }) => ({ completionId, status: "NEEDS_REVIEW", eligible: false, blockers: ["VERIFIED_REVENUE_BASIS_REQUIRED"] }) }, AuditLogModel: { create: async (event) => { audit.push(event); return event; } } }), rows, audit }; };

test("confirmed, paid, settlement, and past date do not create completion", async () => { const { service } = harness(); const result = await service.list({}); assert.deepEqual(result, []); });
test("completion identity is stable by booking and service unit", () => { assert.equal(completionKey({ bookingId: "b1", serviceKey: "P-1" }), completionKey({ bookingId: "b1", serviceKey: "P-1" })); assert.notEqual(completionKey({ bookingId: "b1", serviceKey: "P-1" }), completionKey({ bookingId: "b1", serviceKey: "P-2" })); });
test("authorized admin confirmation requires explicit completion evidence", async () => { const { service, rows } = harness({ bokunOperationalEvidence: { activityStatus: "ARRIVED" } }); const result = await service.create({ input: { bookingReference: "BR-1", serviceKey: "P-1", status: "COMPLETED", evidenceSource: "ADMIN_CONFIRMATION", completedAt: "2026-09-15T10:00:00.000Z", reason: "Admin confirmed delivered service" }, auth: { id: "admin", role: "admin" } }); assert.equal(result.completion.status, "COMPLETED"); assert.equal(result.completion.evidenceSource, "ADMIN_CONFIRMATION"); assert.equal(rows.length, 1); });
test("completion preview delegates to canonical recognition policy", async () => { const { service } = harness(); const preview = await service.recognitionPreview({ completionId: "c1" }); assert.equal(preview.completionId, "c1"); assert.equal(preview.status, "NEEDS_REVIEW"); assert.equal(preview.eligible, false); assert.deepEqual(preview.blockers, ["VERIFIED_REVENUE_BASIS_REQUIRED"]); });

test("no-show and cancellation are not completion revenue candidates", async () => { const { service } = harness(); const noShow = await service.create({ input: { bookingReference: "BR-1", status: "NO_SHOW", evidenceSource: "BOKUN_NO_SHOW", externalStatus: "NO_SHOW" }, auth: { id: "admin", role: "admin" } }); assert.equal(noShow.completion.status, "NO_SHOW"); });

test("confirmed unpaid booking can become completed only through explicit evidence", async () => { const { service, rows, audit } = harness({ bookingStatus: "CONFIRMED", paymentStatus: "UNPAID" }); const pending = await service.create({ input: { bookingReference: "BR-1", serviceKey: "TRANSFER-1", status: "COMPLETION_PENDING", evidenceSource: "DRIVER_CONFIRMATION", reason: "Driver reported drop-off" }, auth: { id: "operator", role: "staff" } }); assert.equal(pending.completion.status, "COMPLETION_PENDING"); assert.equal(pending.completion.verifiedAt, null); const verified = await service.verify({ completionId: pending.completion._id, input: { completedAt: "2026-09-15T10:00:00.000Z", reason: "Admin verified driver evidence" }, auth: { id: "admin", role: "admin" } }); assert.equal(verified.completion.status, "COMPLETED"); assert.equal(verified.completion.verifiedBy, "admin"); assert.equal(rows.length, 1); assert.equal(audit.some((event) => event.action === "SERVICE_COMPLETION_VERIFIED"), true); });

test("one component does not complete a second package component and duplicate is idempotent", async () => { const { service, rows } = harness({ bokunOperationalEvidence: { activityStatus: "ARRIVED" } }); const first = await service.create({ input: { bookingReference: "BR-1", serviceKey: "TRANSFER", status: "COMPLETED", evidenceSource: "ADMIN_CONFIRMATION", completedAt: "2026-09-15T10:00:00.000Z", reason: "Transfer evidence" }, auth: { id: "admin", role: "admin" } }); const second = await service.create({ input: { bookingReference: "BR-1", serviceKey: "STONE-TOWN", status: "COMPLETION_PENDING", evidenceSource: "GUIDE_CONFIRMATION", reason: "Guide evidence" }, auth: { id: "operator", role: "staff" } }); const replay = await service.create({ input: { bookingReference: "BR-1", serviceKey: "TRANSFER", status: "COMPLETED", evidenceSource: "ADMIN_CONFIRMATION", completedAt: "2026-09-15T10:00:00.000Z", reason: "Transfer evidence" }, auth: { id: "admin", role: "admin" } }); assert.equal(rows.length, 2); assert.equal(first.completion.status, "COMPLETED"); assert.equal(second.completion.status, "COMPLETION_PENDING"); assert.equal(replay.replay, true); });

test("only admin verification permission can confirm Bókun arrival", async () => { const { service } = harness({ bokunOperationalEvidence: { activityStatus: "ARRIVED" } }); await assert.rejects(() => service.create({ input: { bookingReference: "BR-1", serviceKey: "P-1", status: "COMPLETED", evidenceSource: "ADMIN_CONFIRMATION", completedAt: "2026-09-15T10:00:00.000Z", reason: "Incorrect actor" }, auth: { id: "staff", role: "staff" } }), { code: "COMPLETION_ADMIN_CONFIRMATION_FORBIDDEN" }); });
test("cancelled booking cannot silently become completed", async () => { const { service } = harness({ bookingStatus: "CANCELLED", bokunOperationalEvidence: { activityStatus: "ARRIVED" } }); await assert.rejects(() => service.create({ input: { bookingReference: "BR-1", serviceKey: "P-1", status: "COMPLETED", evidenceSource: "ADMIN_CONFIRMATION", completedAt: "2026-09-15T10:00:00.000Z", reason: "Incorrect completion" }, auth: { id: "admin", role: "admin" } }), { code: "CANCELLATION_REVIEW_REQUIRED" }); });
