const ACCOUNTING_SCOPE = Object.freeze({
  BOOKING: "BOOKING_ACCOUNTING",
  BUSINESS: "BUSINESS_ACCOUNTING"
});

const SOURCE_MODULE = Object.freeze({
  BOOKING_ACCOUNTING: "BOOKING_ACCOUNTING",
  BUSINESS_ACCOUNTING: "BUSINESS_ACCOUNTING",
  BOOKING: "BOOKING",
  INVOICE: "INVOICE",
  PAYMENT: "PAYMENT",
  REFUND: "REFUND",
  COMMISSION: "COMMISSION",
  CASH_MOVEMENT: "CASH_MOVEMENT",
  MANUAL: "MANUAL"
});

const BUSINESS_UNIT = Object.freeze({
  TOURS: "TOURS",
  TRANSFERS: "TRANSFERS",
  SAFARIS: "SAFARIS",
  CAR_RENTAL: "CAR_RENTAL",
  HOTEL_SERVICES: "HOTEL_SERVICES",
  PHOTOGRAPHY: "PHOTOGRAPHY",
  OTHER: "OTHER",
  GENERAL_COMPANY: "GENERAL_COMPANY",
  UNALLOCATED: "UNALLOCATED"
});

const INCOME_CATEGORY = Object.freeze({
  BOOKING_INCOME_LINK: "BOOKING_INCOME_LINK",
  COMMISSION_INCOME: "COMMISSION_INCOME",
  RENTAL_INCOME: "RENTAL_INCOME",
  SERVICE_INCOME: "SERVICE_INCOME",
  INTEREST_INCOME: "INTEREST_INCOME",
  OTHER_BUSINESS_INCOME: "OTHER_BUSINESS_INCOME",
  MISCELLANEOUS_INCOME: "MISCELLANEOUS_INCOME"
});

const EXPENSE_CATEGORY = Object.freeze({
  OFFICE_RENT: "OFFICE_RENT",
  SALARIES: "SALARIES",
  INTERNET: "INTERNET",
  TELEPHONE: "TELEPHONE",
  ELECTRICITY: "ELECTRICITY",
  WATER: "WATER",
  MARKETING: "MARKETING",
  ADVERTISING: "ADVERTISING",
  SOFTWARE: "SOFTWARE",
  BANK_CHARGES: "BANK_CHARGES",
  INSURANCE: "INSURANCE",
  GOVERNMENT_FEES: "GOVERNMENT_FEES",
  TAXES: "TAXES",
  PROFESSIONAL_FEES: "PROFESSIONAL_FEES",
  OFFICE_SUPPLIES: "OFFICE_SUPPLIES",
  VEHICLE_OVERHEAD: "VEHICLE_OVERHEAD",
  MAINTENANCE: "MAINTENANCE",
  TRAVEL: "TRAVEL",
  STAFF_WELFARE: "STAFF_WELFARE",
  TRAINING: "TRAINING",
  EQUIPMENT: "EQUIPMENT",
  OTHER_OPERATING_EXPENSE: "OTHER_OPERATING_EXPENSE"
});

const EXPENSE_PAYMENT_STATUS = Object.freeze({
  UNPAID: "UNPAID",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
  OVERDUE: "OVERDUE",
  VOID: "VOID"
});

const POSTING_TYPE = Object.freeze({
  BOOKING_NET_CONTRIBUTION: "BOOKING_NET_CONTRIBUTION",
  BOOKING_INCOME_LINK: "BOOKING_INCOME_LINK",
  OTHER_BUSINESS_INCOME: "OTHER_BUSINESS_INCOME",
  OPERATING_EXPENSE: "OPERATING_EXPENSE",
  PAYROLL_EXPENSE: "PAYROLL_EXPENSE",
  OTHER_COMPANY_EXPENSE: "OTHER_COMPANY_EXPENSE",
  RECEIVABLE: "RECEIVABLE",
  PAYABLE: "PAYABLE",
  CASH_MOVEMENT: "CASH_MOVEMENT"
});

const POSTING_DIRECTION = Object.freeze({
  INCOME: "INCOME",
  EXPENSE: "EXPENSE",
  ASSET: "ASSET",
  LIABILITY: "LIABILITY",
  NEUTRAL: "NEUTRAL"
});

const FINANCIAL_ENTRY_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PAID: "PAID",
  VOID: "VOID"
});

const COUNTED_FINANCIAL_STATUSES = Object.freeze([
  FINANCIAL_ENTRY_STATUS.APPROVED,
  FINANCIAL_ENTRY_STATUS.PAID
]);

const GL_ACCOUNT_TYPE = Object.freeze({
  ASSET: "ASSET",
  LIABILITY: "LIABILITY",
  EQUITY: "EQUITY",
  REVENUE: "REVENUE",
  COST_OF_SALES: "COST_OF_SALES",
  EXPENSE: "EXPENSE",
  OTHER_INCOME: "OTHER_INCOME",
  OTHER_EXPENSE: "OTHER_EXPENSE"
});

const GL_ACCOUNT_SUBTYPE = Object.freeze({
  CURRENT_ASSET: "CURRENT_ASSET",
  NON_CURRENT_ASSET: "NON_CURRENT_ASSET",
  CASH: "CASH",
  BANK: "BANK",
  MOBILE_MONEY: "MOBILE_MONEY",
  PROVIDER_CLEARING: "PROVIDER_CLEARING",
  ACCOUNTS_RECEIVABLE: "ACCOUNTS_RECEIVABLE",
  PREPAID_EXPENSE: "PREPAID_EXPENSE",
  FIXED_ASSET: "FIXED_ASSET",
  ACCUMULATED_DEPRECIATION: "ACCUMULATED_DEPRECIATION",
  CURRENT_LIABILITY: "CURRENT_LIABILITY",
  ACCOUNTS_PAYABLE: "ACCOUNTS_PAYABLE",
  SUPPLIER_PAYABLE: "SUPPLIER_PAYABLE",
  TAX_PAYABLE: "TAX_PAYABLE",
  PAYROLL_PAYABLE: "PAYROLL_PAYABLE",
  CUSTOMER_DEPOSIT: "CUSTOMER_DEPOSIT",
  REFUND_PAYABLE: "REFUND_PAYABLE",
  LOAN_PAYABLE: "LOAN_PAYABLE",
  OWNER_EQUITY: "OWNER_EQUITY",
  OWNER_CAPITAL: "OWNER_CAPITAL",
  RETAINED_EARNINGS: "RETAINED_EARNINGS",
  OWNER_DRAWING: "OWNER_DRAWING",
  OPERATING_REVENUE: "OPERATING_REVENUE",
  TOUR_REVENUE: "TOUR_REVENUE",
  TRANSFER_REVENUE: "TRANSFER_REVENUE",
  COMMISSION_REVENUE: "COMMISSION_REVENUE",
  OTHER_SERVICE_REVENUE: "OTHER_SERVICE_REVENUE",
  CONTRA_REVENUE: "CONTRA_REVENUE",
  DIRECT_COST: "DIRECT_COST",
  DIRECT_SUPPLIER_COST: "DIRECT_SUPPLIER_COST",
  DIRECT_TRANSPORT_COST: "DIRECT_TRANSPORT_COST",
  DIRECT_GUIDE_COST: "DIRECT_GUIDE_COST",
  DIRECT_BOAT_COST: "DIRECT_BOAT_COST",
  DIRECT_ACTIVITY_COST: "DIRECT_ACTIVITY_COST",
  OPERATING_EXPENSE: "OPERATING_EXPENSE",
  SALARY_EXPENSE: "SALARY_EXPENSE",
  RENT_EXPENSE: "RENT_EXPENSE",
  MARKETING_EXPENSE: "MARKETING_EXPENSE",
  SOFTWARE_EXPENSE: "SOFTWARE_EXPENSE",
  BANK_FEE_EXPENSE: "BANK_FEE_EXPENSE",
  PAYMENT_PROVIDER_FEE: "PAYMENT_PROVIDER_FEE",
  INSURANCE_EXPENSE: "INSURANCE_EXPENSE",
  OFFICE_EXPENSE: "OFFICE_EXPENSE",
  INTEREST_INCOME: "INTEREST_INCOME",
  OTHER_INCOME: "OTHER_INCOME",
  REFUNDS_AND_ALLOWANCES: "REFUNDS_AND_ALLOWANCES",
  OTHER_EXPENSE: "OTHER_EXPENSE"
});

const GL_ACCOUNT_NORMAL_BALANCE = Object.freeze({
  DEBIT: "DEBIT",
  CREDIT: "CREDIT"
});

const JOURNAL_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  POSTED: "POSTED",
  REVERSED: "REVERSED",
  VOID: "VOID"
});

const ACCOUNTING_PERIOD_STATUS = Object.freeze({
  OPEN: "OPEN",
  SOFT_CLOSED: "SOFT_CLOSED",
  CLOSED: "CLOSED",
  LOCKED: "LOCKED"
});

const GL_POSTING_TYPE = Object.freeze({
  CUSTOMER_INVOICE: "CUSTOMER_INVOICE",
  CUSTOMER_PAYMENT: "CUSTOMER_PAYMENT",
  PROVIDER_FEE: "PROVIDER_FEE",
  PROVIDER_SETTLEMENT: "PROVIDER_SETTLEMENT",
  REFUND_APPROVAL: "REFUND_APPROVAL",
  REFUND_COMPLETION: "REFUND_COMPLETION",
  BOOKING_DIRECT_COST: "BOOKING_DIRECT_COST",
  BUSINESS_EXPENSE: "BUSINESS_EXPENSE",
  BUSINESS_EXPENSE_PAYMENT: "BUSINESS_EXPENSE_PAYMENT",
  BUSINESS_INCOME: "BUSINESS_INCOME",
  OWNER_CAPITAL_INJECTION: "OWNER_CAPITAL_INJECTION",
  OWNER_DRAWING: "OWNER_DRAWING",
  OPENING_BALANCE: "OPENING_BALANCE",
  MANUAL_JOURNAL: "MANUAL_JOURNAL",
  DEPRECIATION: "DEPRECIATION"
});

const GL_MAPPING_KEY = Object.freeze({
  ACCOUNTS_RECEIVABLE: "ACCOUNTS_RECEIVABLE",
  ACCOUNTS_PAYABLE: "ACCOUNTS_PAYABLE",
  CASH: "CASH",
  BANK: "BANK",
  MOBILE_MONEY: "MOBILE_MONEY",
  PESAPAL_CLEARING: "PESAPAL_CLEARING",
  PAYPAL_CLEARING: "PAYPAL_CLEARING",
  DPO_CLEARING: "DPO_CLEARING",
  PAYMENT_PROVIDER_FEE: "PAYMENT_PROVIDER_FEE",
  TOUR_REVENUE: "TOUR_REVENUE",
  TRANSFER_REVENUE: "TRANSFER_REVENUE",
  OTHER_SERVICE_REVENUE: "OTHER_SERVICE_REVENUE",
  SUPPLIER_DIRECT_COST: "SUPPLIER_DIRECT_COST",
  TRANSPORT_DIRECT_COST: "TRANSPORT_DIRECT_COST",
  GUIDE_DIRECT_COST: "GUIDE_DIRECT_COST",
  BOAT_DIRECT_COST: "BOAT_DIRECT_COST",
  REFUND_ALLOWANCE: "REFUND_ALLOWANCE",
  REFUND_PAYABLE: "REFUND_PAYABLE",
  RENT_EXPENSE: "RENT_EXPENSE",
  SOFTWARE_EXPENSE: "SOFTWARE_EXPENSE",
  MARKETING_EXPENSE: "MARKETING_EXPENSE",
  SALARY_EXPENSE: "SALARY_EXPENSE",
  OTHER_INCOME: "OTHER_INCOME",
  OWNER_CAPITAL: "OWNER_CAPITAL",
  OWNER_DRAWING: "OWNER_DRAWING",
  RETAINED_EARNINGS: "RETAINED_EARNINGS",
  ACCUMULATED_DEPRECIATION: "ACCUMULATED_DEPRECIATION",
  DEPRECIATION_EXPENSE: "DEPRECIATION_EXPENSE",
  TAX_PAYABLE: "TAX_PAYABLE",
  TAX_EXPENSE: "TAX_EXPENSE",
  TAX_RECEIVABLE: "TAX_RECEIVABLE"
});

const COST_CENTER_TYPE = Object.freeze({
  OPERATIONS: "OPERATIONS",
  SALES: "SALES",
  MARKETING: "MARKETING",
  FINANCE: "FINANCE",
  ADMINISTRATION: "ADMINISTRATION",
  FLEET: "FLEET",
  OTHER: "OTHER"
});

const FIXED_ASSET_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  DISPOSED: "DISPOSED",
  RETIRED: "RETIRED"
});

const DEPRECIATION_METHOD = Object.freeze({
  STRAIGHT_LINE: "STRAIGHT_LINE"
});

const LEDGER_MIGRATION_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  DRY_RUN: "DRY_RUN",
  READY_FOR_REVIEW: "READY_FOR_REVIEW",
  APPLIED: "APPLIED",
  FAILED: "FAILED"
});

const LEDGER_MIGRATION_CONFIDENCE = Object.freeze({
  HIGH_CONFIDENCE: "HIGH_CONFIDENCE",
  MEDIUM_CONFIDENCE: "MEDIUM_CONFIDENCE",
  MANUAL_REVIEW_REQUIRED: "MANUAL_REVIEW_REQUIRED"
});

module.exports = {
  ACCOUNTING_SCOPE,
  ACCOUNTING_PERIOD_STATUS,
  BUSINESS_UNIT,
  COUNTED_FINANCIAL_STATUSES,
  COST_CENTER_TYPE,
  DEPRECIATION_METHOD,
  EXPENSE_CATEGORY,
  EXPENSE_PAYMENT_STATUS,
  FINANCIAL_ENTRY_STATUS,
  FIXED_ASSET_STATUS,
  GL_ACCOUNT_NORMAL_BALANCE,
  GL_ACCOUNT_SUBTYPE,
  GL_ACCOUNT_TYPE,
  GL_MAPPING_KEY,
  GL_POSTING_TYPE,
  INCOME_CATEGORY,
  JOURNAL_STATUS,
  LEDGER_MIGRATION_CONFIDENCE,
  LEDGER_MIGRATION_STATUS,
  POSTING_DIRECTION,
  POSTING_TYPE,
  SOURCE_MODULE
};
