const ACCOUNTING_SCOPE = Object.freeze({
  BOOKING: "BOOKING_ACCOUNTING",
  BUSINESS: "BUSINESS_ACCOUNTING"
});

const SOURCE_MODULE = Object.freeze({
  BOOKING_ACCOUNTING: "BOOKING_ACCOUNTING",
  BUSINESS_ACCOUNTING: "BUSINESS_ACCOUNTING",
  BOOKING: "BOOKING",
  INVOICE: "INVOICE",
  PAYMENT: "PAYMENT",
  REFUND: "REFUND",
  COMMISSION: "COMMISSION",
  CASH_MOVEMENT: "CASH_MOVEMENT",
  MANUAL: "MANUAL"
});

const BUSINESS_UNIT = Object.freeze({
  TOURS: "TOURS",
  TRANSFERS: "TRANSFERS",
  SAFARIS: "SAFARIS",
  CAR_RENTAL: "CAR_RENTAL",
  HOTEL_SERVICES: "HOTEL_SERVICES",
  PHOTOGRAPHY: "PHOTOGRAPHY",
  OTHER: "OTHER",
  GENERAL_COMPANY: "GENERAL_COMPANY",
  UNALLOCATED: "UNALLOCATED"
});

const INCOME_CATEGORY = Object.freeze({
  BOOKING_INCOME_LINK: "BOOKING_INCOME_LINK",
  COMMISSION_INCOME: "COMMISSION_INCOME",
  RENTAL_INCOME: "RENTAL_INCOME",
  SERVICE_INCOME: "SERVICE_INCOME",
  INTEREST_INCOME: "INTEREST_INCOME",
  OTHER_BUSINESS_INCOME: "OTHER_BUSINESS_INCOME",
  MISCELLANEOUS_INCOME: "MISCELLANEOUS_INCOME"
});

const EXPENSE_CATEGORY = Object.freeze({
  OFFICE_RENT: "OFFICE_RENT",
  SALARIES: "SALARIES",
  INTERNET: "INTERNET",
  TELEPHONE: "TELEPHONE",
  ELECTRICITY: "ELECTRICITY",
  WATER: "WATER",
  MARKETING: "MARKETING",
  ADVERTISING: "ADVERTISING",
  SOFTWARE: "SOFTWARE",
  BANK_CHARGES: "BANK_CHARGES",
  INSURANCE: "INSURANCE",
  GOVERNMENT_FEES: "GOVERNMENT_FEES",
  TAXES: "TAXES",
  PROFESSIONAL_FEES: "PROFESSIONAL_FEES",
  OFFICE_SUPPLIES: "OFFICE_SUPPLIES",
  VEHICLE_OVERHEAD: "VEHICLE_OVERHEAD",
  MAINTENANCE: "MAINTENANCE",
  TRAVEL: "TRAVEL",
  STAFF_WELFARE: "STAFF_WELFARE",
  TRAINING: "TRAINING",
  EQUIPMENT: "EQUIPMENT",
  OTHER_OPERATING_EXPENSE: "OTHER_OPERATING_EXPENSE"
});

const EXPENSE_PAYMENT_STATUS = Object.freeze({
  UNPAID: "UNPAID",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
  OVERDUE: "OVERDUE",
  VOID: "VOID"
});

const POSTING_TYPE = Object.freeze({
  BOOKING_NET_CONTRIBUTION: "BOOKING_NET_CONTRIBUTION",
  BOOKING_INCOME_LINK: "BOOKING_INCOME_LINK",
  OTHER_BUSINESS_INCOME: "OTHER_BUSINESS_INCOME",
  OPERATING_EXPENSE: "OPERATING_EXPENSE",
  PAYROLL_EXPENSE: "PAYROLL_EXPENSE",
  OTHER_COMPANY_EXPENSE: "OTHER_COMPANY_EXPENSE",
  RECEIVABLE: "RECEIVABLE",
  PAYABLE: "PAYABLE",
  CASH_MOVEMENT: "CASH_MOVEMENT"
});

const POSTING_DIRECTION = Object.freeze({
  INCOME: "INCOME",
  EXPENSE: "EXPENSE",
  ASSET: "ASSET",
  LIABILITY: "LIABILITY",
  NEUTRAL: "NEUTRAL"
});

const FINANCIAL_ENTRY_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PAID: "PAID",
  VOID: "VOID"
});

const COUNTED_FINANCIAL_STATUSES = Object.freeze([
  FINANCIAL_ENTRY_STATUS.APPROVED,
  FINANCIAL_ENTRY_STATUS.PAID
]);

module.exports = {
  ACCOUNTING_SCOPE,
  BUSINESS_UNIT,
  COUNTED_FINANCIAL_STATUSES,
  EXPENSE_CATEGORY,
  EXPENSE_PAYMENT_STATUS,
  FINANCIAL_ENTRY_STATUS,
  INCOME_CATEGORY,
  POSTING_DIRECTION,
  POSTING_TYPE,
  SOURCE_MODULE
};
