import { PaymentTruthBadge, SettlementBadge, PaymentTruthDetails } from './BookingPaymentState';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Dropdown, Offcanvas } from 'react-bootstrap';
import { BsArrowClockwise, BsArrowUpRight, BsCashCoin, BsCreditCard, BsExclamationCircle, BsFileEarmarkText, BsPrinter, BsThreeDots, BsWallet2 } from 'react-icons/bs';
import { bookingHref, dateLabel, humanize, invoiceIsOverdue, invoiceMoney, statusTone, summarizeInvoicePage } from './invoiceView';

export function InvoiceSkeleton({ compact = false }) {
  return <div className={`iv-skeleton ${compact ? 'compact' : ''}`} role="status" aria-label="Loading invoices">{Array.from({ length: compact ? 3 : 6 }, (_, i) => <span key={i} />)}</div>;
}
export function InvoiceError({ error, onRetry, title = 'Unable to load invoices.' }) {
  return <div className="iv-error" role="alert"><BsExclamationCircle aria-hidden="true" /><div><strong>{title}</strong><p>{error}</p></div><button type="button" className="iv-button" onClick={onRetry}><BsArrowClockwise aria-hidden="true" />Retry</button></div>;
}
export function InvoiceStatus({ value }) { return <span className={`iv-status ${statusTone(value)}`}>{humanize(value || 'Unknown')}</span>; }
export function InvoiceSummaryCards({ items, loading }) {
  const groups = summarizeInvoicePage(items);
  const metrics = [['total', 'Total Invoiced', BsFileEarmarkText, 'blue'], ['amountPaid', 'Locally allocated', BsCreditCard, 'green'], ['balanceDue', 'Accounting balance', BsWallet2, 'amber'], ['amountRefunded', 'Refunded', BsCashCoin, 'purple']];
  return <div className="iv-kpis">{metrics.map(([key, label, Icon, tone]) => <section className={`iv-kpi ${tone}`} key={key} aria-label={label} aria-busy={loading}>{loading ? <InvoiceSkeleton compact /> : <><span className="iv-kpi-icon"><Icon aria-hidden="true" /></span><div><h2>{label}</h2>{groups.length ? groups.map(group => <strong key={group.currency}>{invoiceMoney(group[key], group.currency)}</strong>) : <strong>—</strong>}<p>{items.length} invoices on this page</p></div></>}</section>)}</div>;
}
export function InvoiceActions({ invoice, onView }) {
  return <Dropdown align="end" onClick={event => event.stopPropagation()}><Dropdown.Toggle variant="light" className="iv-action-toggle" aria-label={`Actions for ${invoice.invoiceNumber}`}><BsThreeDots aria-hidden="true" /></Dropdown.Toggle><Dropdown.Menu popperConfig={{ strategy: 'fixed' }}><Dropdown.Item onClick={() => onView(invoice)}>View invoice</Dropdown.Item>{invoice.bookingReference && <Dropdown.Item as={Link} to={bookingHref(invoice.bookingReference)}>View booking</Dropdown.Item>}</Dropdown.Menu></Dropdown>;
}
const Balance = ({ invoice }) => <strong className={invoiceIsOverdue(invoice) ? 'iv-negative' : Number(invoice.balanceDue) === 0 ? 'iv-settled' : 'iv-balance'}>{invoiceMoney(invoice.balanceDue, invoice.currency)}</strong>;
const Identity = ({ invoice }) => <><strong>{invoice.clientName || 'Customer not recorded'}</strong>{invoice.bookingReference && <Link to={bookingHref(invoice.bookingReference)} onClick={event => event.stopPropagation()}>{invoice.bookingReference}</Link>}{invoice.tourName && <small>{invoice.tourName}</small>}{invoice.bookingStatus === 'cancelled' && <small>Booking cancelled</small>}</>;
export function InvoiceTable({ items, onView }) {
  return <><div className="iv-table-scroll" role="region" aria-label="Invoices table" tabIndex={0}><table><thead><tr><th>Invoice</th><th>Customer / Booking</th><th>Customer payment</th><th>Settlement</th><th className="money">Total</th><th className="money">Local allocated</th><th className="money">Refunded</th><th className="money">Accounting balance</th><th>Updated</th><th><span className="visually-hidden">Actions</span></th></tr></thead><tbody>{items.map(invoice => <tr key={invoice.id || invoice.invoiceNumber} onClick={() => onView(invoice)}><td><button className="iv-invoice-link" type="button" onClick={event => { event.stopPropagation(); onView(invoice); }}>{invoice.invoiceNumber}</button><small>{dateLabel(invoice.issueDate)}</small></td><td className="iv-identity"><Identity invoice={invoice} /></td><td><PaymentTruthBadge payment={invoice.bookingPayment} /></td><td><SettlementBadge settlement={invoice.settlement} /></td><td className="money">{invoiceMoney(invoice.total, invoice.currency)}</td><td className="money">{invoiceMoney(invoice.amountPaid, invoice.currency)}</td><td className="money">{invoiceMoney(invoice.amountRefunded, invoice.currency)}</td><td className="money"><Balance invoice={invoice} /></td><td><small>{dateLabel(invoice.updatedAt)}</small></td><td><InvoiceActions invoice={invoice} onView={onView} /></td></tr>)}</tbody></table></div>
    <div className="iv-mobile-list">{items.map(invoice => <article className="iv-mobile-card" key={invoice.id || invoice.invoiceNumber}><div className="iv-mobile-heading"><button type="button" className="iv-invoice-link" onClick={() => onView(invoice)}>{invoice.invoiceNumber}</button><PaymentTruthBadge payment={invoice.bookingPayment} /><SettlementBadge settlement={invoice.settlement} /></div><div className="iv-identity"><Identity invoice={invoice} /></div><dl>{[['Total', 'total'], ['Local allocated', 'amountPaid'], ['Refunded', 'amountRefunded']].map(([label, field]) => <div key={field}><dt>{label}</dt><dd>{invoiceMoney(invoice[field], invoice.currency)}</dd></div>)}<div><dt>Accounting balance {invoiceIsOverdue(invoice) ? '· Past due' : ''}</dt><dd><Balance invoice={invoice} /></dd></div></dl><footer><small>Updated {dateLabel(invoice.updatedAt)}</small><div><button type="button" className="iv-button" onClick={() => onView(invoice)}>View invoice</button><InvoiceActions invoice={invoice} onView={onView} /></div></footer></article>)}</div></>;
}
export function InvoicePagination({ page, limit, total, onPage, onLimit, disabled }) {
  const pages = Math.max(1, Math.ceil(total / limit));
  const start = Math.max(1, Math.min(page - 2, pages - 4));
  return <footer className="iv-pagination"><span>Showing {total ? (page - 1) * limit + 1 : 0}–{Math.min(page * limit, total)} of {total} invoices</span><nav aria-label="Invoice pages"><button type="button" disabled={disabled || page <= 1} onClick={() => onPage(page - 1)}>Previous</button>{Array.from({ length: Math.min(5, pages) }, (_, i) => start + i).map(value => <button type="button" className="iv-page-number" aria-current={page === value ? 'page' : undefined} key={value} disabled={disabled} onClick={() => onPage(value)}>{value}</button>)}<button type="button" disabled={disabled || page >= pages} onClick={() => onPage(page + 1)}>Next</button></nav><label>Rows per page<select value={limit} onChange={event => onLimit(Number(event.target.value))} disabled={disabled}>{[25, 50, 100].map(value => <option key={value}>{value}</option>)}</select></label></footer>;
}
export function InvoiceDetailsDrawer({ invoice, state, onClose }) {
  const [tab, setTab] = useState('overview');
  const detail = state.data;
  const currency = detail?.currency;
  return <Offcanvas show={Boolean(invoice)} onHide={onClose} placement="end" className="iv-drawer" aria-labelledby="iv-detail-title"><Offcanvas.Header closeButton><Offcanvas.Title id="iv-detail-title">Invoice Details</Offcanvas.Title></Offcanvas.Header><Offcanvas.Body>
    {state.loading ? <InvoiceSkeleton /> : state.error ? <InvoiceError error={state.error} onRetry={state.retry} title="Unable to load invoice details." /> : detail && <>
      <PaymentTruthBadge payment={detail.bookingPayment} /><PaymentTruthDetails record={detail} /><h2 className="iv-detail-number">{detail.invoiceNumber}</h2><p className="iv-detail-dates">Issued {dateLabel(detail.issueDate)}{detail.dueDate && <><br />Due {dateLabel(detail.dueDate)}</>}</p>
      <div className="iv-detail-actions"><button type="button" className="iv-button" onClick={() => window.print()}><BsPrinter aria-hidden="true" />Print / Save PDF</button>{detail.bookingReference && <Link className="iv-button" to={bookingHref(detail.bookingReference)} onClick={onClose}>View booking <BsArrowUpRight aria-hidden="true" /></Link>}</div>
      <nav className="iv-detail-tabs" aria-label="Invoice detail sections">{[['overview', 'Overview'], ['payments', 'Payments & refunds'], ['activity', 'Dates']].map(([key, label]) => <button type="button" key={key} aria-pressed={tab === key} onClick={() => setTab(key)}>{label}</button>)}</nav>
      <div className={`iv-overview ${tab !== 'overview' ? 'iv-tab-hidden' : ''}`}>
        <section className="iv-detail-card"><h3>Customer</h3><strong>{detail.clientName || 'Not recorded'}</strong>{detail.clientEmail && <p>{detail.clientEmail}</p>}{detail.clientPhone && <p>{detail.clientPhone}</p>}<h3 className="iv-subheading">Booking</h3><strong>{detail.bookingReference || 'Not linked'}</strong>{detail.tourName && <p>{detail.tourName}</p>}{detail.bookedOption && <p>{detail.bookedOption}</p>}{detail.tourDate && <p>Travel date: {dateLabel(detail.tourDate)}</p>}<p>Booking status: {humanize(detail.bookingStatus || 'unknown')}</p></section>
        <section className="iv-detail-card"><h3>Invoice Items</h3>{detail.items?.length ? <div className="iv-items-scroll" tabIndex={0} role="region" aria-label="Invoice line items"><table><thead><tr><th>Description</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>{detail.items.map((item, index) => <tr key={item._id || index}><td>{item.label || 'Item'}</td><td>{item.quantity ?? '—'}</td><td>{invoiceMoney(item.unitPrice, currency)}</td><td>{invoiceMoney(item.total, currency)}</td></tr>)}</tbody></table></div> : <p>Item breakdown is not available for this invoice.</p>}<dl className="iv-detail-totals">{[['Subtotal', 'subtotal'], ['Discount', 'discount'], ['Tax', 'tax'], ['Total', 'total']].map(([label, field]) => <div key={field}><dt>{label}</dt><dd>{invoiceMoney(detail[field], currency)}</dd></div>)}</dl></section>
      </div>
      <section className={`iv-detail-card iv-payment-summary ${tab === 'activity' ? 'iv-tab-hidden' : ''}`}><h3>Local Accounting Summary</h3><p>Accounting status: <InvoiceStatus value={detail.paymentStatus} /></p><p className="iv-note">This balance is not necessarily money due from the traveler. Customer payment and channel settlement are separate.</p><dl className="iv-detail-totals">{[['Total paid', 'amountPaid'], ['Total refunded', 'amountRefunded'], ['Net paid', 'netAmountPaid'], ['Accounting balance', 'balanceDue']].map(([label, field]) => <div key={field}><dt>{label}</dt><dd>{invoiceMoney(detail[field], currency)}</dd></div>)}</dl>{detail.paymentMethod && <p>Payment method: {humanize(detail.paymentMethod)}</p>}{tab === 'payments' && <p className="iv-note">These are the invoice’s stored payment and refund totals. Individual transaction history is not supplied by this invoice endpoint.</p>}</section>
      {tab === 'activity' && <section className="iv-detail-card"><h3>Recorded Dates</h3><dl className="iv-detail-totals">{[['Created', detail.createdAt], ['Issued', detail.issueDate], ['Due', detail.dueDate], ['Last updated', detail.updatedAt]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{dateLabel(value)}</dd></div>)}</dl><p className="iv-note">A full activity log is not available for this invoice.</p></section>}
      {detail.paymentTerms && <section className="iv-detail-card"><h3>Payment Terms</h3><p>{detail.paymentTerms}</p></section>}
    </>}
  </Offcanvas.Body></Offcanvas>;
}
