const REPORT_GROUP = Object.freeze({
  EXECUTIVE: "EXECUTIVE",
  BOOKING: "BOOKING",
  SALES: "SALES",
  PRODUCT: "PRODUCT",
  CHANNEL: "CHANNEL",
  CUSTOMER: "CUSTOMER",
  AGENT: "AGENT",
  SUPPLIER: "SUPPLIER",
  VEHICLE: "VEHICLE",
  DRIVER: "DRIVER",
  GUIDE: "GUIDE",
  BOOKING_ACCOUNTING: "BOOKING_ACCOUNTING",
  BUSINESS_ACCOUNTING: "BUSINESS_ACCOUNTING",
  EXPENSE: "EXPENSE",
  REFUND: "REFUND",
  RECEIVABLES: "RECEIVABLES",
  PAYABLES: "PAYABLES",
  CASH_FLOW: "CASH_FLOW",
  PROFITABILITY: "PROFITABILITY",
  TAX_SUPPORT: "TAX_SUPPORT",
  RECONCILIATION: "RECONCILIATION",
  CUSTOM: "CUSTOM",
  EXPORT_HISTORY: "EXPORT_HISTORY"
});

const REPORT_TYPE = Object.freeze({
  DAILY_MANAGEMENT_REPORT: "DAILY_MANAGEMENT_REPORT",
  WEEKLY_MANAGEMENT_REPORT: "WEEKLY_MANAGEMENT_REPORT",
  MONTHLY_MANAGEMENT_REPORT: "MONTHLY_MANAGEMENT_REPORT",
  QUARTERLY_MANAGEMENT_REPORT: "QUARTERLY_MANAGEMENT_REPORT",
  ANNUAL_MANAGEMENT_REPORT: "ANNUAL_MANAGEMENT_REPORT",
  MULTI_YEAR_COMPARISON: "MULTI_YEAR_COMPARISON",
  EXECUTIVE_BUSINESS_SUMMARY: "EXECUTIVE_BUSINESS_SUMMARY",
  SALES_SUMMARY: "SALES_SUMMARY",
  PRODUCT_BEST_SELLERS: "PRODUCT_BEST_SELLERS",
  PRODUCT_REVENUE_RANKING: "PRODUCT_REVENUE_RANKING",
  PRODUCT_PROFIT_RANKING: "PRODUCT_PROFIT_RANKING",
  PRODUCT_MARGIN_RANKING: "PRODUCT_MARGIN_RANKING",
  PRODUCT_LOW_MARGIN: "PRODUCT_LOW_MARGIN",
  PRODUCT_LOSS_MAKING: "PRODUCT_LOSS_MAKING",
  PRODUCT_CANCELLATION_REPORT: "PRODUCT_CANCELLATION_REPORT",
  PRODUCT_REFUND_REPORT: "PRODUCT_REFUND_REPORT",
  PRODUCT_COST_VARIANCE_REPORT: "PRODUCT_COST_VARIANCE_REPORT",
  PRODUCT_PROFITABILITY: "PRODUCT_PROFITABILITY",
  CHANNEL_COMPARISON_REPORT: "CHANNEL_COMPARISON_REPORT",
  CHANNEL_NET_PROFIT_REPORT: "CHANNEL_NET_PROFIT_REPORT",
  CHANNEL_MARGIN_REPORT: "CHANNEL_MARGIN_REPORT",
  CHANNEL_REFUND_REPORT: "CHANNEL_REFUND_REPORT",
  CHANNEL_CANCELLATION_REPORT: "CHANNEL_CANCELLATION_REPORT",
  CHANNEL_LOSS_MAKING: "CHANNEL_LOSS_MAKING",
  CHANNEL_PROFITABILITY: "CHANNEL_PROFITABILITY",
  PROFITABILITY_OVERVIEW: "PROFITABILITY_OVERVIEW",
  LOSS_MAKING_REPORT: "LOSS_MAKING_REPORT",
  MANAGEMENT_PROFIT_LOSS_REPORT: "MANAGEMENT_PROFIT_LOSS_REPORT",
  MANAGEMENT_CASH_FLOW_REPORT: "MANAGEMENT_CASH_FLOW_REPORT",
  INCOME_REPORT: "INCOME_REPORT",
  OPERATING_EXPENSE_REPORT: "OPERATING_EXPENSE_REPORT",
  PAYROLL_SUMMARY: "PAYROLL_SUMMARY",
  SUPPLIER_EXPENSE_REPORT: "SUPPLIER_EXPENSE_REPORT",
  RECEIVABLES_AGING_REPORT: "RECEIVABLES_AGING_REPORT",
  PAYABLES_AGING_REPORT: "PAYABLES_AGING_REPORT",
  ASSET_REGISTER: "ASSET_REGISTER",
  TREND_SUMMARY: "TREND_SUMMARY",
  BUSINESS_ACCOUNTING_FOUNDATION: "BUSINESS_ACCOUNTING_FOUNDATION"
});

const REPORT_AVAILABILITY = Object.freeze({
  AVAILABLE: "AVAILABLE",
  PLANNED: "PLANNED"
});

const REPORT_EXPORT_FORMAT = Object.freeze({
  CSV: "CSV",
  EXCEL: "EXCEL",
  PDF: "PDF",
  PRINT: "PRINT"
});

const REPORT_PERMISSION = Object.freeze({
  VIEW_REPORTS: "reports.view",
  EXPORT_REPORTS: "reports.export",
  VIEW_PROFIT: "finance.view_profit",
  VIEW_COMPANY_PROFIT: "finance.view_company_profit"
});

module.exports = {
  REPORT_AVAILABILITY,
  REPORT_EXPORT_FORMAT,
  REPORT_GROUP,
  REPORT_PERMISSION,
  REPORT_TYPE
};
