const CRM_LEAD_STATUS = Object.freeze({
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  QUALIFIED: "QUALIFIED",
  UNQUALIFIED: "UNQUALIFIED",
  CONVERTED: "CONVERTED",
  LOST: "LOST",
  ARCHIVED: "ARCHIVED"
});

const CRM_LEAD_SOURCE = Object.freeze({
  WEBSITE: "WEBSITE",
  WHATSAPP: "WHATSAPP",
  EMAIL: "EMAIL",
  PHONE: "PHONE",
  WALK_IN: "WALK_IN",
  VIATOR_INQUIRY: "VIATOR_INQUIRY",
  GETYOURGUIDE_INQUIRY: "GETYOURGUIDE_INQUIRY",
  HOTEL: "HOTEL",
  AGENT: "AGENT",
  B2B: "B2B",
  SOCIAL_MEDIA: "SOCIAL_MEDIA",
  REFERRAL: "REFERRAL",
  OTHER: "OTHER"
});

const CRM_OPPORTUNITY_STAGE = Object.freeze({
  NEW: "NEW",
  QUALIFIED: "QUALIFIED",
  NEEDS_ANALYSIS: "NEEDS_ANALYSIS",
  QUOTE_PREPARATION: "QUOTE_PREPARATION",
  QUOTE_SENT: "QUOTE_SENT",
  NEGOTIATION: "NEGOTIATION",
  AWAITING_CUSTOMER: "AWAITING_CUSTOMER",
  READY_TO_BOOK: "READY_TO_BOOK",
  WON: "WON",
  LOST: "LOST"
});

const CRM_QUOTE_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  INTERNAL_REVIEW: "INTERNAL_REVIEW",
  APPROVED: "APPROVED",
  SENT: "SENT",
  VIEWED: "VIEWED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  CONVERTED: "CONVERTED",
  CANCELLED: "CANCELLED"
});

const CRM_QUOTE_LINE_ITEM_TYPE = Object.freeze({
  BOKUN_PRODUCT: "BOKUN_PRODUCT",
  CUSTOM_SERVICE: "CUSTOM_SERVICE",
  TRANSFER: "TRANSFER",
  TOUR: "TOUR",
  SAFARI: "SAFARI",
  ACCOMMODATION: "ACCOMMODATION",
  ADD_ON: "ADD_ON",
  DISCOUNT: "DISCOUNT",
  OTHER_SERVICE: "OTHER_SERVICE"
});

const CRM_FOLLOW_UP_TYPE = Object.freeze({
  CALL: "CALL",
  WHATSAPP: "WHATSAPP",
  EMAIL: "EMAIL",
  QUOTE_FOLLOW_UP: "QUOTE_FOLLOW_UP",
  PAYMENT_FOLLOW_UP: "PAYMENT_FOLLOW_UP",
  DECISION_FOLLOW_UP: "DECISION_FOLLOW_UP",
  POST_TRIP_FOLLOW_UP: "POST_TRIP_FOLLOW_UP",
  CUSTOM: "CUSTOM"
});

const CRM_FOLLOW_UP_STATUS = Object.freeze({
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  MISSED: "MISSED",
  CANCELLED: "CANCELLED"
});

const CRM_TASK_STATUS = Object.freeze({
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  DONE: "DONE",
  CANCELLED: "CANCELLED"
});

const CRM_TASK_RELATED_ENTITY_TYPE = Object.freeze({
  LEAD: "LEAD",
  OPPORTUNITY: "OPPORTUNITY",
  CUSTOMER: "CUSTOMER",
  QUOTE: "QUOTE",
  BOOKING: "BOOKING",
  OTHER: "OTHER"
});

const CRM_PRIORITY = Object.freeze({
  LOW: "LOW",
  NORMAL: "NORMAL",
  HIGH: "HIGH",
  URGENT: "URGENT"
});

const CRM_LOST_REASON = Object.freeze({
  PRICE_TOO_HIGH: "PRICE_TOO_HIGH",
  NO_RESPONSE: "NO_RESPONSE",
  CHANGED_DESTINATION: "CHANGED_DESTINATION",
  BOOKED_COMPETITOR: "BOOKED_COMPETITOR",
  DATES_CHANGED: "DATES_CHANGED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  PAYMENT_ISSUE: "PAYMENT_ISSUE",
  CANCELLED_TRIP: "CANCELLED_TRIP",
  OTHER: "OTHER"
});

const CRM_B2B_PARTNER_TYPE = Object.freeze({
  TRAVEL_AGENT: "TRAVEL_AGENT",
  HOTEL: "HOTEL",
  TOUR_OPERATOR: "TOUR_OPERATOR",
  CORPORATE_CLIENT: "CORPORATE_CLIENT",
  B2B_PARTNER: "B2B_PARTNER",
  OTHER: "OTHER"
});

const CRM_B2B_PARTNER_STATUS = Object.freeze({
  PROSPECT: "PROSPECT",
  CONTACTED: "CONTACTED",
  PROPOSAL_SENT: "PROPOSAL_SENT",
  NEGOTIATION: "NEGOTIATION",
  AGREEMENT: "AGREEMENT",
  ACTIVE_PARTNER: "ACTIVE_PARTNER",
  INACTIVE: "INACTIVE",
  LOST: "LOST"
});

const CRM_B2B_COMMISSION_MODEL = Object.freeze({
  NONE: "NONE",
  PERCENTAGE: "PERCENTAGE",
  FIXED_AMOUNT: "FIXED_AMOUNT",
  NET_RATE: "NET_RATE",
  CUSTOM: "CUSTOM"
});

const CRM_B2B_NET_RATE_MODEL = Object.freeze({
  NONE: "NONE",
  STANDARD_NET_RATE: "STANDARD_NET_RATE",
  PRODUCT_SPECIFIC: "PRODUCT_SPECIFIC",
  CONTRACTED: "CONTRACTED",
  CUSTOM: "CUSTOM"
});

const CUSTOMER_LIFECYCLE_STAGE = Object.freeze({
  LEAD: "LEAD",
  PROSPECT: "PROSPECT",
  FIRST_TIME_CUSTOMER: "FIRST_TIME_CUSTOMER",
  REPEAT_CUSTOMER: "REPEAT_CUSTOMER",
  VIP: "VIP",
  INACTIVE: "INACTIVE",
  LOST: "LOST"
});

const CUSTOMER_SEGMENT = Object.freeze({
  DIRECT: "DIRECT",
  AGENT: "AGENT",
  B2B: "B2B",
  VIP: "VIP",
  REPEAT: "REPEAT",
  HIGH_VALUE: "HIGH_VALUE",
  FAMILY: "FAMILY",
  GROUP: "GROUP",
  CORPORATE: "CORPORATE",
  OTHER: "OTHER"
});

const CUSTOMER_DUPLICATE_STATUS = Object.freeze({
  CLEAN: "CLEAN",
  POSSIBLE_DUPLICATE: "POSSIBLE_DUPLICATE",
  MERGED: "MERGED",
  DISMISSED: "DISMISSED"
});

const DUPLICATE_CANDIDATE_STATUS = Object.freeze({
  OPEN: "OPEN",
  REVIEWED: "REVIEWED",
  MERGED: "MERGED",
  DISMISSED: "DISMISSED"
});

const CUSTOMER_TIMELINE_EVENT_TYPE = Object.freeze({
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_VIEWED: "CUSTOMER_VIEWED",
  DUPLICATE_PREVENTED: "DUPLICATE_PREVENTED",
  POSSIBLE_DUPLICATE_FLAGGED: "POSSIBLE_DUPLICATE_FLAGGED",
  DUPLICATE_REVIEWED: "DUPLICATE_REVIEWED",
  NOTE_ADDED: "NOTE_ADDED",
  LEAD_CONVERTED_TO_CUSTOMER: "LEAD_CONVERTED_TO_CUSTOMER",
  LEAD_CONVERTED_TO_OPPORTUNITY: "LEAD_CONVERTED_TO_OPPORTUNITY",
  OPPORTUNITY_STAGE_CHANGED: "OPPORTUNITY_STAGE_CHANGED",
  QUOTE_CREATED: "QUOTE_CREATED",
  QUOTE_APPROVED: "QUOTE_APPROVED",
  QUOTE_SENT: "QUOTE_SENT",
  QUOTE_ACCEPTED: "QUOTE_ACCEPTED",
  QUOTE_REJECTED: "QUOTE_REJECTED",
  FOLLOW_UP_CREATED: "FOLLOW_UP_CREATED",
  FOLLOW_UP_COMPLETED: "FOLLOW_UP_COMPLETED",
  TASK_CREATED: "TASK_CREATED",
  TASK_COMPLETED: "TASK_COMPLETED",
  COMMUNICATION_LOGGED: "COMMUNICATION_LOGGED",
  BOOKING_LINKED: "BOOKING_LINKED",
  PAYMENT_OBSERVED: "PAYMENT_OBSERVED",
  REFUND_OBSERVED: "REFUND_OBSERVED"
});

const CRM_COMMUNICATION_CHANNEL = Object.freeze({
  EMAIL: "EMAIL",
  WHATSAPP: "WHATSAPP",
  PHONE: "PHONE",
  SMS: "SMS",
  IN_PERSON: "IN_PERSON",
  OTHER: "OTHER"
});

const CRM_COMMUNICATION_DIRECTION = Object.freeze({
  INBOUND: "INBOUND",
  OUTBOUND: "OUTBOUND",
  INTERNAL_NOTE: "INTERNAL_NOTE"
});

const CRM_COMMUNICATION_STATUS = Object.freeze({
  MANUAL_LOGGED: "MANUAL_LOGGED"
});

module.exports = {
  CRM_B2B_COMMISSION_MODEL,
  CRM_B2B_NET_RATE_MODEL,
  CRM_B2B_PARTNER_STATUS,
  CRM_B2B_PARTNER_TYPE,
  CRM_COMMUNICATION_CHANNEL,
  CRM_COMMUNICATION_DIRECTION,
  CRM_COMMUNICATION_STATUS,
  CRM_FOLLOW_UP_STATUS,
  CRM_FOLLOW_UP_TYPE,
  CRM_LOST_REASON,
  CRM_LEAD_SOURCE,
  CRM_LEAD_STATUS,
  CRM_OPPORTUNITY_STAGE,
  CRM_PRIORITY,
  CRM_QUOTE_LINE_ITEM_TYPE,
  CRM_QUOTE_STATUS,
  CRM_TASK_RELATED_ENTITY_TYPE,
  CRM_TASK_STATUS,
  CUSTOMER_DUPLICATE_STATUS,
  CUSTOMER_LIFECYCLE_STAGE,
  CUSTOMER_SEGMENT,
  CUSTOMER_TIMELINE_EVENT_TYPE,
  DUPLICATE_CANDIDATE_STATUS
};
