const express = require("express");

const authRoutes = require("./auth.routes");
const usersRoutes = require("./users.routes");
const bokunRoutes = require("./bokun.routes");
const toursRoutes = require("./tours.routes");
const bookingsRoutes = require("./bookings.routes");
const customersRoutes = require("./customers.routes");
const invoicesRoutes = require("./invoices.routes");
const agentsRoutes = require("./agents.routes");
const commissionsRoutes = require("./commissions.routes");
const offersRoutes = require("./offers.routes");
const paymentsRoutes = require("./payments.routes");
const webhooksRoutes = require("./webhooks.routes");
const reportsRoutes = require("./reports.routes");
const marketingRoutes = require("./marketing.routes");
const reviewsRoutes = require("./reviews.routes");
const bookingRequestsRoutes = require("./bookingRequests.routes");
const adminBookingRequestsRoutes = require("./adminBookingRequests.routes");
const analyticsRoutes = require("./analytics.routes");
const accountingRoutes = require("./accounting.routes");
const crmRoutes = require("./crm.routes");
const businessAccountingRoutes = require("./businessAccounting.routes");
const businessExpensesRoutes = require("./businessExpenses.routes");
const businessIncomeRoutes = require("./businessIncome.routes");
const reportCenterRoutes = require("./reportCenter.routes");
const auditControlRoutes = require("./auditControl.routes");
const dataQualityRoutes = require("./dataQuality.routes");
const opsControlRoutes = require("./opsControl.routes");
const disasterRecoveryRoutes = require("./disasterRecovery.routes");
const systemHealthRoutes = require("./systemHealth.routes");
const performanceReviewRoutes = require("./performanceReview.routes");
const productionReadinessRoutes = require("./productionReadiness.routes");

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/bokun", bokunRoutes);
router.use("/tours", toursRoutes);
router.use("/bookings", bookingsRoutes);
router.use("/customers", customersRoutes);
router.use("/invoices", invoicesRoutes);
router.use("/agent", agentsRoutes);
router.use("/agents", agentsRoutes);
router.use("/commissions", commissionsRoutes);
router.use("/offers", offersRoutes);
router.use("/payments", paymentsRoutes);
router.use("/webhooks", webhooksRoutes);
router.use("/reports", reportsRoutes);
router.use("/marketing", marketingRoutes);
router.use("/reviews", reviewsRoutes);
router.use("/admin/analytics", analyticsRoutes);
router.use("/admin/accounting", accountingRoutes);
router.use("/admin/crm", crmRoutes);
router.use("/admin/report-center", reportCenterRoutes);
router.use("/admin/audit-control", auditControlRoutes);
router.use("/admin/data-quality", dataQualityRoutes);
router.use("/admin/ops-control", opsControlRoutes);
router.use("/admin/disaster-recovery", disasterRecoveryRoutes);
router.use("/admin/system-health", systemHealthRoutes);
router.use("/admin/performance-review", performanceReviewRoutes);
router.use("/admin/production-readiness", productionReadinessRoutes);
router.use("/admin/business-accounting", businessAccountingRoutes);
router.use("/admin/business-expenses", businessExpensesRoutes);
router.use("/admin/business-income", businessIncomeRoutes);
router.use("/", bookingRequestsRoutes);
router.use("/admin", adminBookingRequestsRoutes);

module.exports = router;
