const express = require("express");
const { authenticate } = require("../middleware/auth");
const { authorizePermission } = require("../middleware/rbac");
const validateRequest = require("../middleware/validateRequest");
const { PERMISSIONS } = require("../security/permissions");
const controller = require("../controllers/serviceCompletion.controller");
const schemas = require("../validators/serviceCompletion.validation");
const router = express.Router();
router.use(authenticate, authorizePermission(PERMISSIONS.SERVICE_COMPLETION_VIEW));
router.get("/", validateRequest(schemas.listSchema), controller.list);
router.get("/booking/:bookingReference/review", validateRequest(schemas.reviewSchema), controller.review);
router.get("/:completionId", validateRequest(schemas.idSchema), controller.detail);
router.post("/", authorizePermission(PERMISSIONS.SERVICE_COMPLETION_CREATE), validateRequest(schemas.createSchema), controller.create);
router.post("/:completionId/verify", authorizePermission(PERMISSIONS.SERVICE_COMPLETION_VERIFY), validateRequest(schemas.verifySchema), controller.verify);
router.post("/:completionId/reverse", authorizePermission(PERMISSIONS.SERVICE_COMPLETION_REVERSE), validateRequest(schemas.reverseSchema), controller.reverse);
router.post("/:completionId/revenue-preview", authorizePermission(PERMISSIONS.REVENUE_RECOGNITION_PREVIEW), validateRequest(schemas.idSchema), controller.previewRevenue);
router.post("/:completionId/revenue-post", authorizePermission(PERMISSIONS.REVENUE_RECOGNITION_POST), validateRequest(schemas.idSchema), controller.postRevenue);
router.post("/:completionId/revenue-evidence", authorizePermission(PERMISSIONS.GL_APPROVE_JOURNAL), validateRequest(schemas.evidenceSchema), controller.verifyRevenueEvidence);
router.post("/:completionId/revenue-reverse", authorizePermission(PERMISSIONS.REVENUE_RECOGNITION_REVERSE), validateRequest(schemas.revenueReverseSchema), controller.reverseRevenue);
module.exports = router;
