const ANALYTICS_TIME_ZONE = "Africa/Dar_es_Salaam";

const ANALYTICS_PERIOD = Object.freeze({
  TODAY: "TODAY",
  YESTERDAY: "YESTERDAY",
  THIS_WEEK: "THIS_WEEK",
  LAST_WEEK: "LAST_WEEK",
  THIS_MONTH: "THIS_MONTH",
  LAST_MONTH: "LAST_MONTH",
  THIS_QUARTER: "THIS_QUARTER",
  LAST_QUARTER: "LAST_QUARTER",
  THIS_YEAR: "THIS_YEAR",
  LAST_YEAR: "LAST_YEAR",
  CUSTOM: "CUSTOM",
  MULTI_YEAR: "MULTI_YEAR",
  LIFETIME: "LIFETIME"
});

const ANALYTICS_COMPARE_MODE = Object.freeze({
  NONE: "NONE",
  PREVIOUS_PERIOD: "PREVIOUS_PERIOD",
  PREVIOUS_MONTH: "PREVIOUS_MONTH",
  PREVIOUS_QUARTER: "PREVIOUS_QUARTER",
  PREVIOUS_YEAR: "PREVIOUS_YEAR",
  CUSTOM: "CUSTOM"
});

const ANALYTICS_GRANULARITY = Object.freeze({
  DAY: "DAY",
  WEEK: "WEEK",
  MONTH: "MONTH",
  QUARTER: "QUARTER",
  YEAR: "YEAR"
});

const ANALYTICS_DATE_DIMENSION = Object.freeze({
  ACCOUNTING_TRANSACTION_DATE: "ACCOUNTING_TRANSACTION_DATE",
  BOKUN_BOOKING_CREATED_DATE: "BOKUN_BOOKING_CREATED_DATE",
  BOKUN_TRAVEL_DATE: "BOKUN_TRAVEL_DATE",
  PAYMENT_DATE: "PAYMENT_DATE",
  REFUND_DATE: "REFUND_DATE",
  EXPENSE_DATE: "EXPENSE_DATE",
  SETTLEMENT_DATE: "SETTLEMENT_DATE",
  BOOKING_CREATED_AT: "BOOKING_CREATED_AT",
  INVOICE_ISSUE_DATE: "INVOICE_ISSUE_DATE"
});

const ANALYTICS_PROFIT_VIEW = Object.freeze({
  ACTUAL: "ACTUAL",
  ESTIMATED: "ESTIMATED"
});

const ANALYTICS_CURRENCY_VIEW = Object.freeze({
  ORIGINAL: "ORIGINAL",
  USD: "USD",
  TZS: "TZS",
  COMPANY_BASE: "COMPANY_BASE"
});

const ANALYTICS_SOURCE_LAYER = Object.freeze({
  OPERATIONS: "OPERATIONS",
  BOOKING_ACCOUNTING: "BOOKING_ACCOUNTING",
  BUSINESS_ACCOUNTING: "BUSINESS_ACCOUNTING",
  ANALYTICS: "ANALYTICS"
});

const ANALYTICS_RANGE_BOUNDARY = "START_INCLUSIVE_END_EXCLUSIVE";

module.exports = {
  ANALYTICS_COMPARE_MODE,
  ANALYTICS_CURRENCY_VIEW,
  ANALYTICS_DATE_DIMENSION,
  ANALYTICS_GRANULARITY,
  ANALYTICS_PERIOD,
  ANALYTICS_PROFIT_VIEW,
  ANALYTICS_RANGE_BOUNDARY,
  ANALYTICS_SOURCE_LAYER,
  ANALYTICS_TIME_ZONE
};
