import { useCallback, useEffect, useMemo, useState } from "react";
import { Button, Form, Modal, Spinner } from "react-bootstrap";
import {
  BsArrowClockwise, BsCalendar3, BsCheck2Circle, BsDownload, BsExclamationTriangle,
  BsFileEarmarkText, BsFilter, BsPlusLg, BsSearch, BsWallet2
} from "react-icons/bs";
import { Link, useSearchParams } from "react-router-dom";
import { createBusinessExpense, fetchAccountsPayableDashboard } from "../../api/adminApi";
import { ADMIN_PERMISSIONS } from "../../config/adminNavigation";
import { useAuthContext } from "../../context/AuthContext";
import ErrorAlert from "../../components/common/ErrorAlert";
import { formatCurrency } from "../../utils/formatters";

const TABS = [
  ["all", "All Invoices"], ["outstanding", "Outstanding"], ["overdue", "Overdue"],
  ["paid", "Paid"], ["draft", "Drafts"]
];
const LIMITS = [10, 25, 50, 100];
const CATEGORIES = ["OFFICE_RENT", "SALARIES", "INTERNET", "TELEPHONE", "ELECTRICITY", "WATER", "MARKETING", "ADVERTISING", "SOFTWARE", "BANK_CHARGES", "INSURANCE", "GOVERNMENT_FEES", "TAXES", "PROFESSIONAL_FEES", "OFFICE_SUPPLIES", "VEHICLE_OVERHEAD", "MAINTENANCE", "TRAVEL", "STAFF_WELFARE", "TRAINING", "EQUIPMENT", "OTHER_OPERATING_EXPENSE"];
const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => { const value = new Date(); return new Date(Date.UTC(value.getUTCFullYear(), value.getUTCMonth(), 1)).toISOString().slice(0, 10); };
const labelize = (value = "") => String(value || "").toLowerCase().split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" ");
const money = (value, currency) => value === null || value === undefined ? "Separated by currency" : formatCurrency(Number(value || 0), currency || "USD");
const date = (value) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Not set";
const updateQuery = (setter, updates) => setter((current) => { const next = new URLSearchParams(current); Object.entries(updates).forEach(([key, value]) => value === "" ? next.delete(key) : next.set(key, String(value))); return next; });

const Kpi = ({ icon: Icon, label, value, detail, tone }) => <article className={`ap-kpi ${tone}`}><span><Icon /></span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article>;

const AgingChart = ({ values = {}, currency }) => {
  const rows = [["Current", values.current], ["31-60 days", values.days31to60], ["61-90 days", values.days61to90], ["91+ days", values.days91plus]];
  const max = Math.max(1, ...rows.map(([, value]) => Number(value || 0)));
  return <div className="ap-aging-chart" aria-label="Aging of payables"><div className="ap-chart-bars">{rows.map(([label, value]) => <div key={label}><strong>{money(value, currency)}</strong><i style={{ height: `${Math.max(4, Number(value || 0) / max * 100)}%` }} /><span>{label}</span></div>)}</div></div>;
};

const SupplierChart = ({ rows = [], currency }) => {
  const total = rows.reduce((sum, row) => sum + Number(row.amount || 0), 0);
  if (!rows.length) return <div className="ap-empty compact">No supplier balances for this period.</div>;
  return <div className="ap-supplier-chart"><div className="ap-donut" aria-label="Payables by supplier"><strong>{money(total, currency)}</strong><small>Outstanding</small></div><div className="ap-supplier-legend">{rows.map((row, index) => <div key={row.name}><i className={`c${index + 1}`} /><span>{row.name}</span><strong>{total ? `${(Number(row.amount) / total * 100).toFixed(1)}%` : "0%"}</strong></div>)}</div></div>;
};

const BillForm = ({ show, onHide, onSaved }) => {
  const initial = { supplierName: "", category: "OFFICE_SUPPLIES", description: "", amount: "", currency: "TZS", expenseDate: today(), dueDate: "", sourceReference: "", notes: "", status: "DRAFT" };
  const [form, setForm] = useState(initial);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const submit = async (event) => {
    event.preventDefault(); setSaving(true); setError("");
    try {
      await createBusinessExpense({ category: form.category, description: form.description, amount: form.amount, currency: form.currency, baseCurrency: form.currency, expenseDate: form.expenseDate, dueDate: form.dueDate || undefined, sourceReference: form.sourceReference, supplier: { name: form.supplierName }, notes: form.notes, paymentStatus: "UNPAID", status: form.status });
      setForm(initial); onSaved(); onHide();
    } catch (err) { setError(err.message || "Unable to create supplier bill."); }
    finally { setSaving(false); }
  };
  const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  return <Modal show={show} onHide={onHide} centered size="lg"><Form onSubmit={submit}><Modal.Header closeButton><Modal.Title>New Bill / Invoice</Modal.Title></Modal.Header><Modal.Body><ErrorAlert error={error} /><div className="ap-bill-form"><Form.Group><Form.Label>Supplier</Form.Label><Form.Control required value={form.supplierName} onChange={set("supplierName")} /></Form.Group><Form.Group><Form.Label>Bill reference</Form.Label><Form.Control value={form.sourceReference} onChange={set("sourceReference")} /></Form.Group><Form.Group className="wide"><Form.Label>Description</Form.Label><Form.Control required value={form.description} onChange={set("description")} /></Form.Group><Form.Group><Form.Label>Category</Form.Label><Form.Select value={form.category} onChange={set("category")}>{CATEGORIES.map((item) => <option key={item} value={item}>{labelize(item)}</option>)}</Form.Select></Form.Group><Form.Group><Form.Label>Amount</Form.Label><Form.Control required min="0.01" step="0.01" type="number" value={form.amount} onChange={set("amount")} /></Form.Group><Form.Group><Form.Label>Currency</Form.Label><Form.Select value={form.currency} onChange={set("currency")}><option>TZS</option><option>USD</option></Form.Select></Form.Group><Form.Group><Form.Label>Invoice date</Form.Label><Form.Control required type="date" value={form.expenseDate} onChange={set("expenseDate")} /></Form.Group><Form.Group><Form.Label>Due date</Form.Label><Form.Control type="date" value={form.dueDate} onChange={set("dueDate")} /></Form.Group><Form.Group><Form.Label>Entry status</Form.Label><Form.Select value={form.status} onChange={set("status")}><option value="DRAFT">Draft</option><option value="SUBMITTED">Submitted</option></Form.Select></Form.Group><Form.Group className="wide"><Form.Label>Notes</Form.Label><Form.Control as="textarea" rows={2} value={form.notes} onChange={set("notes")} /></Form.Group></div></Modal.Body><Modal.Footer><Button variant="outline-secondary" onClick={onHide}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Spinner size="sm" /> : <BsPlusLg />} Create Bill</Button></Modal.Footer></Form></Modal>;
};

const AdminAccountsPayablePage = () => {
  const { user } = useAuthContext();
  const [params, setParams] = useSearchParams();
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(""); const [showBill, setShowBill] = useState(false); const [search, setSearch] = useState(params.get("search") || "");
  const filters = useMemo(() => ({ fromDate: params.get("fromDate") || monthStart(), toDate: params.get("toDate") || today(), search: params.get("search") || "", supplier: params.get("supplier") || "", status: params.get("status") || "all", currency: params.get("currency") || "", dueFrom: params.get("dueFrom") || "", dueTo: params.get("dueTo") || "", page: params.get("page") || "1", limit: params.get("limit") || "10" }), [params]);
  const canCreate = (user?.permissions || []).includes(ADMIN_PERMISSIONS.BUSINESS_EXPENSE_WRITE) || ["admin", "super_admin"].includes(user?.role);
  const load = useCallback(async (silent = false) => { silent ? setRefreshing(true) : setLoading(true); setError(""); try { setData(await fetchAccountsPayableDashboard(filters)); } catch (err) { setError(err.message || "Unable to load Accounts Payable."); } finally { setLoading(false); setRefreshing(false); } }, [filters]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const timer = setTimeout(() => { if (search !== filters.search) updateQuery(setParams, { search, page: 1 }); }, 400); return () => clearTimeout(timer); }, [search, filters.search, setParams]);
  const summary = data?.summary || {}; const pagination = data?.pagination || {}; const currency = summary.reportingCurrency || summary.currencies?.[0]?.currency || "USD"; const tabs = data?.tabCounts || {};
  const reset = () => { setSearch(""); setParams({ fromDate: monthStart(), toDate: today(), status: "all", page: "1", limit: filters.limit }); };
  const exportCsv = () => { const rows = data?.items || []; const csv = [["Date","Bill","Supplier","Reference","Description","Due Date","Amount","Paid","Balance","Currency","Status"], ...rows.map((row) => [row.expenseDate,row.expenseReference,row.supplier?.name,row.sourceReference,row.description,row.dueDate,row.amount,row.paidAmount,row.outstandingAmount,row.reportingCurrency,row.displayStatus])].map((row) => row.map((value) => `"${String(value ?? "").replace(/"/g, '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "accounts-payable.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <main className="accounts-payable-page"><header className="ap-header"><div><nav>Business Accounting / <strong>Payables (AP)</strong></nav><h1>Accounts Payable (AP)</h1><p>Manage supplier invoices, payments, due dates, and outstanding balances.</p></div><div className="ap-header-actions"><label><BsCalendar3 /><input type="date" value={filters.fromDate} onChange={(event) => updateQuery(setParams, { fromDate: event.target.value, page: 1 })} /><span>-</span><input type="date" value={filters.toDate} onChange={(event) => updateQuery(setParams, { toDate: event.target.value, page: 1 })} /></label><Button variant="outline-primary" onClick={exportCsv}><BsDownload /> Export CSV</Button><Button variant="outline-secondary" onClick={() => load(true)} disabled={refreshing}>{refreshing ? <Spinner size="sm" /> : <BsArrowClockwise />} Refresh</Button><Button onClick={() => setShowBill(true)} disabled={!canCreate} title={!canCreate ? "Business expense write permission is required" : "Create supplier bill"}><BsPlusLg /> New Bill / Invoice</Button></div></header><ErrorAlert error={error} />
    {loading ? <div className="ap-skeleton">{Array.from({ length: 8 }).map((_, index) => <span key={index} />)}</div> : <><section className="ap-kpis"><Kpi icon={BsFileEarmarkText} label="Total Supplier Invoices" value={summary.invoiceCount || 0} detail="Counted bills in selected period" tone="blue" /><Kpi icon={BsWallet2} label={`Total Amount${currency ? ` (${currency})` : ""}`} value={money(summary.totalAmount, currency)} detail={summary.mixedCurrencies ? "Separated by reporting currency" : "Approved and paid supplier bills"} tone="green" /><Kpi icon={BsExclamationTriangle} label={`Outstanding${currency ? ` (${currency})` : ""}`} value={money(summary.outstanding, currency)} detail="Authoritative unpaid bill balance" tone="red" /><Kpi icon={BsCheck2Circle} label="Paid This Month" value={money(summary.paidThisMonth, currency)} detail="Bills with confirmed paid status" tone="green" /></section>
    {summary.mixedCurrencies ? <section className="ap-currency-strip">{summary.currencies.map((row) => <span key={row.currency}><strong>{row.currency}</strong> Amount {money(row.amount, row.currency)} · Outstanding {money(row.outstanding, row.currency)}</span>)}</section> : null}
    <section className="ap-analytics"><article className="ap-panel"><h2>Aging of Payables</h2><AgingChart values={data?.aging} currency={currency} /></article><article className="ap-panel"><h2>Payables by Supplier</h2><SupplierChart rows={data?.suppliers} currency={currency} /></article><article className="ap-panel ap-account-summary"><h2>Account Summary</h2><dl><div><dt>AP Subledger</dt><dd>{money(data?.reconciliation?.subledgerBalance, currency)}</dd></div><div><dt>General Ledger AP</dt><dd>{money(data?.reconciliation?.generalLedgerBalance, currency)}</dd></div><div><dt>Difference</dt><dd>{money(data?.reconciliation?.difference, currency)}</dd></div><div><dt>Active Suppliers</dt><dd>{summary.activeSuppliers || 0}</dd></div></dl><span className={data?.reconciliation?.status === "RECONCILED" ? "ok" : "review"}>{labelize(data?.reconciliation?.status || "unavailable")}</span></article></section>
    {data?.dataQuality?.length ? <div className="ap-quality"><BsExclamationTriangle /><div><strong>AP data needs attention</strong>{data.dataQuality.slice(0, 3).map((issue) => <p key={`${issue.code}-${issue.reference || "global"}`}>{issue.reference ? `${issue.reference}: ` : ""}{issue.message}</p>)}</div></div> : null}
    <section className="ap-register"><div className="ap-tabs">{TABS.map(([key, label]) => <button key={key} className={filters.status === key ? "active" : ""} onClick={() => updateQuery(setParams, { status: key, page: 1 })}>{label} ({tabs[key === "draft" ? "drafts" : key] || 0})</button>)}</div><div className="ap-filters"><label><BsSearch /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by supplier, invoice number, reference..." /></label><Form.Select value={filters.currency} onChange={(event) => updateQuery(setParams, { currency: event.target.value, page: 1 })}><option value="">All Currencies</option><option>TZS</option><option>USD</option></Form.Select><Form.Control type="date" value={filters.dueFrom} onChange={(event) => updateQuery(setParams, { dueFrom: event.target.value, page: 1 })} aria-label="Due from" /><Form.Control type="date" value={filters.dueTo} onChange={(event) => updateQuery(setParams, { dueTo: event.target.value, page: 1 })} aria-label="Due to" /><Button variant="outline-secondary" disabled title="Additional filters require dedicated persisted bill fields"><BsFilter /> More Filters</Button><Button variant="outline-secondary" onClick={reset}><BsArrowClockwise /> Reset</Button></div>
    {data?.items?.length ? <><div className="ap-table-wrap"><table><thead><tr><th>Date</th><th>Invoice #</th><th>Supplier</th><th>Reference</th><th>Description</th><th>Due Date</th><th>Amount</th><th>Paid</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.items.map((row) => <tr key={row.id || row.expenseReference}><td>{date(row.expenseDate)}</td><td><strong>{row.expenseReference}</strong></td><td>{row.supplier?.name || "Unassigned"}</td><td>{row.sourceReference || "-"}</td><td>{row.description}</td><td className={row.overdue ? "overdue-date" : ""}>{date(row.dueDate)}{row.overdue ? <small>Overdue</small> : null}</td><td className="num">{money(row.amount, row.reportingCurrency)}</td><td className="num">{money(row.paidAmount, row.reportingCurrency)}</td><td className="num">{money(row.outstandingAmount, row.reportingCurrency)}</td><td><span className={`ap-status ${row.displayStatus}`}>{labelize(row.displayStatus)}</span></td><td><Link to={`/admin/business-accounting/general-ledger?accountCode=2010&search=${encodeURIComponent(row.expenseReference)}&view=account`}>Ledger</Link></td></tr>)}</tbody></table></div><div className="ap-mobile-list">{data.items.map((row) => <article key={row.id || row.expenseReference}><div><strong>{row.supplier?.name || "Unassigned supplier"}</strong><span className={`ap-status ${row.displayStatus}`}>{labelize(row.displayStatus)}</span></div><h3>{row.expenseReference}</h3><p>{row.description}</p><dl><div><dt>Invoice</dt><dd>{date(row.expenseDate)}</dd></div><div><dt>Due</dt><dd>{date(row.dueDate)}{row.overdue ? " · Overdue" : ""}</dd></div><div><dt>Amount</dt><dd>{money(row.amount, row.reportingCurrency)}</dd></div><div><dt>Paid</dt><dd>{money(row.paidAmount, row.reportingCurrency)}</dd></div><div><dt>Outstanding</dt><dd>{money(row.outstandingAmount, row.reportingCurrency)}</dd></div></dl><Link to={`/admin/business-accounting/general-ledger?accountCode=2010&search=${encodeURIComponent(row.expenseReference)}&view=account`}>View Ledger</Link></article>)}</div></> : <div className="ap-empty"><BsFileEarmarkText /><strong>No supplier bills found.</strong><p>{filters.search || filters.status !== "all" ? "No bills match these filters." : "Create a supplier bill to start tracking accounts payable."}</p><Button onClick={filters.search || filters.status !== "all" ? reset : () => setShowBill(true)} disabled={!canCreate && filters.status === "all"}>{filters.search || filters.status !== "all" ? "Reset Filters" : "New Bill / Invoice"}</Button></div>}
    <footer className="ap-pagination"><span>Showing {pagination.from || 0}-{pagination.to || 0} of {pagination.total || 0} invoices</span><div><Button variant="outline-secondary" disabled={!pagination.hasPrevious} onClick={() => updateQuery(setParams, { page: Number(filters.page) - 1 })}>Previous</Button><strong>{pagination.page || 1}</strong><Button variant="outline-secondary" disabled={!pagination.hasNext} onClick={() => updateQuery(setParams, { page: Number(filters.page) + 1 })}>Next</Button><Form.Select value={filters.limit} onChange={(event) => updateQuery(setParams, { limit: event.target.value, page: 1 })}>{LIMITS.map((limit) => <option key={limit} value={limit}>{limit} / page</option>)}</Form.Select></div></footer></section></>}
    <BillForm show={showBill} onHide={() => setShowBill(false)} onSaved={() => load(true)} />
  </main>;
};

export default AdminAccountsPayablePage;
