import { useState } from "react";
import { Badge, Button, Card, Form, Table } from "react-bootstrap";
import { previewAccountingPosting } from "../../api/adminApi";

export default function AdminGlPostingPreviewPage() {
  const [input, setInput] = useState({ completionId: "" });
  const [state, setState] = useState({ loading: false, error: "", data: null });
  const run = async (event) => { event.preventDefault(); setState({ loading: true, error: "", data: null }); try { setState({ loading: false, error: "", data: await previewAccountingPosting(input) }); } catch (error) { setState({ loading: false, error: error.message || "Unable to evaluate preview.", data: null }); } };
  const data = state.data;
  return <main className="admin-page-container"><header className="mb-4"><p className="text-muted mb-1">Business Accounting / Preview Only</p><h1>GL Posting Preview</h1><p className="text-muted">Preview Policy V1 accounting events. Posting is disabled.</p></header>{state.error ? <div className="alert alert-danger">{state.error}</div> : null}<Card className="mb-4"><Card.Body><Form onSubmit={run} className="d-flex gap-2"><Form.Control required placeholder="Service completion ID" value={input.completionId} onChange={(event) => setInput({ completionId: event.target.value })} /><Button type="submit" disabled={state.loading}>Preview</Button></Form></Card.Body></Card>{data ? <Card><Card.Body><div className="d-flex justify-content-between"><h2 className="h5">Accounting Preview</h2><Badge bg={data.eligibility === "SAFE_TO_POST" ? "success" : "warning"}>{data.eligibility}</Badge></div><dl className="row"><dt className="col-sm-3">Policy</dt><dd className="col-sm-9">{data.policy?.id} v{data.policy?.version}</dd><dt className="col-sm-3">Commercial amount</dt><dd className="col-sm-9">{data.commercialAmount || "Unavailable"} {data.currency || ""}</dd><dt className="col-sm-3">Posting date</dt><dd className="col-sm-9">{data.postingDate || "Unavailable"}</dd></dl><Table responsive><thead><tr><th>Account</th><th>Description</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{(data.journalLines || []).map((line) => <tr key={`${line.accountCode}-${line.description}`}><td>{line.accountCode}</td><td>{line.description}</td><td>{line.debit}</td><td>{line.credit}</td></tr>)}</tbody></Table><p className="mb-1">Total debit: {data.totalDebit} | Total credit: {data.totalCredit}</p>{data.blockers?.length ? <div className="alert alert-warning">{data.blockers.map((blocker) => <div key={blocker.code}><strong>{blocker.code}</strong>: {blocker.message}</div>)}</div> : null}<small className="text-muted">Preview only. No AccountingPosting, RevenueRecognition, JournalEntry, or JournalLine was created.</small></Card.Body></Card> : null}</main>;
}